/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.awt.Font;
import java.awt.Frame;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.NumberFormatter;
import com.mycompany.test.Main;
import java.awt.Color;
import java.util.Random;
import javax.swing.BorderFactory;

public class compare extends javax.swing.JFrame {
    private JTextField[] txtArrays, txtArrays1;
    private JLabel[] lbArrays, lbArrays1;
    private int num, num1;
    private int[] arrays, arrays1;  

    public compare() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(input.DISPOSE_ON_CLOSE);
    }
    
     public void createArray(){
        deleteArrays();
        num = (Integer)spSoPT.getValue();
        lbArrays = new JLabel[num];
        txtArrays = new JTextField[num];
        arrays = new int [num];
        
        arrays1 = new int [num];

        for(int i=0; i<num; i++){
            lbArrays[i] = new JLabel("A"+i);

            txtArrays[i] = new JTextField();

            add(lbArrays[i]);
            add(txtArrays[i]);
            
            txtArrays[i].setText(String.valueOf(arrays[i]));
            
            lbArrays[i].setSize(40,30);
            lbArrays[i].setFont(new Font("Tahoma", Font.BOLD, 18));

            if((0<=i) && (i<=14)){
                lbArrays[i].setLocation(180*(i+1)/3, 80);
                
            }
            txtArrays[i].setSize(50,30);
            txtArrays[i].setLocation(lbArrays[i].getX()-10, lbArrays[i].getY()+30);
        }
        setVisible(true);
        validate();
        repaint();
    }
     
    public void createRandom() {
		Random rand = new Random();
                
                if((num!=0)) {
                    
                    for (int i = 0; i < num; i++) {
                            int ranNum = rand.nextInt(101);
                            txtArrays[i].setText(String.valueOf(ranNum));
                            arrays[i] = ranNum;
                    }
                }else{
                    for (int i = 0; i < num; i++) {
			int ranNum = rand.nextInt(101);
			txtArrays[i].setText(String.valueOf(ranNum));
			arrays[i] = ranNum;
                    }
                }               
		setState(2);
	}
    
    
   public void deleteArrays(){
        for(int i=0; i<num; i++){
            lbArrays[i].setVisible(false);
            txtArrays[i].setVisible(false);
            remove(lbArrays[i]);
            remove(txtArrays[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        spSoPT = new javax.swing.JSpinner();
        btnTaomang = new javax.swing.JButton();
        btnXacnhan = new javax.swing.JButton();
        Cb_day1 = new javax.swing.JComboBox<>();
        Cb_day2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Số phần tử mảng (tối đa 15)");

        spSoPT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        btnTaomang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTaomang.setText("Tạo mảng");
        btnTaomang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomangActionPerformed(evt);
            }
        });

        btnXacnhan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnXacnhan.setText("Xác nhận");
        btnXacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacnhanActionPerformed(evt);
            }
        });

        Cb_day1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Cb_day1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interchange Sort", "Selection Sort", "Bubble Sort", "Insertion Sort", "Shell Sort", "Heap Sort", "Quick Sort", "Merge Sort" }));

        Cb_day2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        Cb_day2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Interchange Sort", "Selection Sort", "Bubble Sort", "Insertion Sort", "Shell Sort", "Heap Sort", "Quick Sort", "Merge Sort" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Chọn giải thuật dãy 1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Chọn giải thuật dãy 2");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setText("Ngẫu nhiên");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cb_day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnTaomang)
                                    .addComponent(Cb_day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addContainerGap(222, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(spSoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXacnhan)
                        .addGap(55, 55, 55))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spSoPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaomang)
                    .addComponent(btnXacnhan)
                    .addComponent(jButton1))
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cb_day1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cb_day2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        spSoPT.setModel(new javax.swing.SpinnerNumberModel(2, 0, 15, 1));

        // Code adding the component to the parent container - not shown here
        JFormattedTextField txt = ((JSpinner.NumberEditor) spSoPT.getEditor()).getTextField();
        ((NumberFormatter) txt.getFormatter()).setAllowsInvalid(false);
        spSoPT.setValue(Integer.valueOf("2"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacnhanActionPerformed(java.awt.event.ActionEvent evt) {   
        for(int i=0; i<num; i++){
            if("".equals(txtArrays[i].getText())){
                JOptionPane.showMessageDialog(null, "Phần tử A"+i+" bị bỏ trống!");
            }
            arrays[i] = (int) Integer.parseInt(txtArrays[i].getText());
            arrays1[i] = (int) Integer.parseInt(txtArrays[i].getText());
            System.out.println(arrays[i]);
            System.out.println(arrays1[i]);
        }
        
        Frame[] listFrames = Frame.getFrames();
        ((Main)listFrames[0]).setArray(arrays);
        ((Main)listFrames[0]).setArray_2(arrays1);
        //((Main)listFrames[0]).Filewriter_sosanh(arrays, num);
        
        String value1 = (String) Cb_day1.getSelectedItem();
        String value2 = (String) Cb_day2.getSelectedItem();
        
        if(value1 == "Interchange Sort"){
            ((Main)listFrames[0]).InterchangeSort();
            ((Main)listFrames[0]).waitEnd();
        }else{
            if(value1 == "Selection Sort"){
            ((Main)listFrames[0]).SelectionSort();
            ((Main)listFrames[0]).waitEnd();
            }else{
                if(value1 == "Bubble Sort"){
                ((Main)listFrames[0]).BubbleSort();
                ((Main)listFrames[0]).waitEnd();
                }else{
                    if(value1 == "Insertion Sort"){
                    ((Main)listFrames[0]).InsertionSort();
                    ((Main)listFrames[0]).waitEnd();
                    }else{
                        if(value1 == "Shell Sort"){
                        ((Main)listFrames[0]).ShellSort();
                        ((Main)listFrames[0]).waitEnd();
                        }else{
                            if(value1 == "Heap Sort"){
                            ((Main)listFrames[0]).HeapSort();
                            ((Main)listFrames[0]).threadReLocate();
                            ((Main)listFrames[0]).waitEnd();
                            }else{
                                if(value1 == "Quick Sort"){
                                ((Main)listFrames[0]).QuickSort();
                                ((Main)listFrames[0]).waitEnd();
                                }else{
                                    if(value1 == "Merge Sort"){
                                    ((Main)listFrames[0]).MergeSort();
                                    ((Main)listFrames[0]).waitEnd();
                                }
                        }
                    }
                }
            }
        }}}
        if(value2 == "Interchange Sort"){
            ((Main)listFrames[0]).InterchangeSort_2();
            ((Main)listFrames[0]).waitEnd_2();
        }else{
            if(value2 == "Selection Sort"){
            ((Main)listFrames[0]).SelectionSort_2();
            ((Main)listFrames[0]).waitEnd_2();
            }else{
                if(value2 == "Bubble Sort"){
                ((Main)listFrames[0]).BubbleSort_2();
                ((Main)listFrames[0]).waitEnd_2();
                }else{
                    if(value2 == "Insertion Sort"){
                    ((Main)listFrames[0]).InsertionSort_2();
                    ((Main)listFrames[0]).waitEnd_2();
                    }else{
                        if(value2 == "Shell Sort"){
                        ((Main)listFrames[0]).ShellSort_2();
                        ((Main)listFrames[0]).waitEnd_2();
                        }else{
                            if(value2 == "Heap Sort"){
                            ((Main)listFrames[0]).HeapSort_2();
                            ((Main)listFrames[0]).threadReLocate_2();
                            ((Main)listFrames[0]).waitEnd_2();
                            }else{
                                if(value2 == "Quick Sort"){
                                ((Main)listFrames[0]).QuickSort_2();
                                ((Main)listFrames[0]).waitEnd_2();
                                }else{
                                    if(value2 == "Merge Sort"){
                                    ((Main)listFrames[0]).MergeSort_2();
                                    ((Main)listFrames[0]).waitEnd_2();
                                }
                        }
                    }
                }
            }
        }}}
        
        
        if(num!=0){
            dispose();  
        }
        else {
            JOptionPane.showMessageDialog(null, "Tạo dữ liệu mảng không thành công!");
            dispose();
        }
       

                                           
        
    }                                        

    private void btnTaomangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomangActionPerformed

        createArray();
    }//GEN-LAST:event_btnTaomangActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        createRandom();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Cb_day1;
    private javax.swing.JComboBox<String> Cb_day2;
    private javax.swing.JButton btnTaomang;
    private javax.swing.JButton btnXacnhan;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSpinner spSoPT;
    // End of variables declaration//GEN-END:variables
}
