/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.test;

import java.awt.Font;
import java.awt.Frame;
import javax.swing.JFormattedTextField;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.text.NumberFormatter;
import com.mycompany.test.Main;

public class input extends javax.swing.JFrame {

    private JTextField[] txtArrays;
    private JLabel[] lbArrays;
    private int num;
    private int[] arrays;  

    public input() {
        initComponents();
        setLocationRelativeTo(null);
        setVisible(true);
        setDefaultCloseOperation(input.DISPOSE_ON_CLOSE);
    }
    
     public void createArray(){
        deleteArrays();
        num = (Integer)spSoPT.getValue();
        lbArrays = new JLabel[num];
        txtArrays = new JTextField[num];
        arrays = new int [num];
        
        for(int i=0; i<num; i++){
            lbArrays[i] = new JLabel("A"+i);
            txtArrays[i] = new JTextField();
            
            add(lbArrays[i]);
            add(txtArrays[i]);
            
            lbArrays[i].setSize(40,30);
            lbArrays[i].setFont(new Font("Tahoma", Font.BOLD, 18));

            if((0<=i) && (i<=14)){
                lbArrays[i].setLocation(180*(i+1)/3, 80);
                
            }
            txtArrays[i].setSize(50,30);
            txtArrays[i].setLocation(lbArrays[i].getX()-10, lbArrays[i].getY()+30);
        }
        setVisible(true);
        validate();
        repaint();
    }
    
   public void deleteArrays(){
        for(int i=0; i<num; i++){
            lbArrays[i].setVisible(false);
            txtArrays[i].setVisible(false);
            remove(lbArrays[i]);
            remove(txtArrays[i]);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        spSoPT = new javax.swing.JSpinner();
        btnTaomang = new javax.swing.JButton();
        btnXacnhan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Số phần tử mảng (tối đa 15)");

        spSoPT.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        btnTaomang.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnTaomang.setText("Tạo mảng");
        btnTaomang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaomangActionPerformed(evt);
            }
        });

        btnXacnhan.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnXacnhan.setText("Xác nhận");
        btnXacnhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacnhanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(spSoPT, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(btnTaomang)
                .addGap(43, 43, 43)
                .addComponent(btnXacnhan)
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spSoPT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTaomang)
                    .addComponent(btnXacnhan))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        spSoPT.setModel(new javax.swing.SpinnerNumberModel(2, 0, 15, 1));

        // Code adding the component to the parent container - not shown here
        JFormattedTextField txt = ((JSpinner.NumberEditor) spSoPT.getEditor()).getTextField();
        ((NumberFormatter) txt.getFormatter()).setAllowsInvalid(false);
        spSoPT.setValue(Integer.valueOf("2"));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacnhanActionPerformed(java.awt.event.ActionEvent evt) {   
        Frame[] listFrames = Frame.getFrames();
        for(int i=0; i<num; i++){ 
            if("".equals(txtArrays[i].getText())){
                JOptionPane.showMessageDialog(null, "Phần tử A"+i+" bị bỏ trống!");
            }
            arrays[i] = (int) Integer.parseInt(txtArrays[i].getText());
            System.out.println(arrays[i]);
        }
        
        ((Main)listFrames[0]).setArray(arrays);
        ((Main)listFrames[0]).Filewriter(arrays, num);

        if(num!=0){
            JOptionPane.showMessageDialog(null, "Tạo dữ liệu mảng thành công!");
            dispose();  
        }
        else {
            JOptionPane.showMessageDialog(null, "Tạo dữ liệu mảng không thành công!");
            dispose();
        }
       

                                          
        
    }                                        

    private void btnTaomangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaomangActionPerformed
        createArray();
    }//GEN-LAST:event_btnTaomangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(input.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new input().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTaomang;
    private javax.swing.JButton btnXacnhan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner spSoPT;
    // End of variables declaration//GEN-END:variables
}
